# Dict of popular Indonesian stock tickers and their company names.
# This list covers major market caps, LQ45, and highly active stocks across different sectors.
IDX_POPULAR_STOCKS = {
    "BBCA.JK": "Bank Central Asia Tbk.",
    "BBRI.JK": "Bank Rakyat Indonesia (Persero) Tbk.",
    "BMRI.JK": "Bank Mandiri (Persero) Tbk.",
    "BBNI.JK": "Bank Negara Indonesia (Persero) Tbk.",
    "TLKM.JK": "Telkom Indonesia (Persero) Tbk.",
    "ASII.JK": "Astra International Tbk.",
    "UNVR.JK": "Unilever Indonesia Tbk.",
    "ICBP.JK": "Indofood CBP Sukses Makmur Tbk.",
    "INDF.JK": "Indofood Sukses Makmur Tbk.",
    "GOTO.JK": "GoTo Gojek Tokopedia Tbk.",
    "ADRO.JK": "Adaro Energy Indonesia Tbk.",
    "MDKA.JK": "Merdeka Copper Gold Tbk.",
    "ANTM.JK": "Aneka Tambang Tbk.",
    "PGAS.JK": "Perusahaan Gas Negara Tbk.",
    "KLBF.JK": "Kalbe Farma Tbk.",
    "CPIN.JK": "Charoen Pokphand Indonesia Tbk.",
    "AMRT.JK": "Sumber Alfaria Trijaya Tbk. (Alfamart)",
    "BRMS.JK": "Bumi Resources Minerals Tbk.",
    "BRPT.JK": "Barito Pacific Tbk.",
    "TPIA.JK": "Chandra Asri Petrochemical Tbk.",
    "BREN.JK": "Barito Renewables Energy Tbk.",
    "CUAN.JK": "Petrindo Jaya Kreasi Tbk.",
    "INCO.JK": "Vale Indonesia Tbk.",
    "PTBA.JK": "Bukit Asam Tbk.",
    "ITMG.JK": "Indo Tambangraya Megah Tbk.",
    "HRUM.JK": "Harum Energy Tbk.",
    "UNTR.JK": "United Tractors Tbk.",
    "MYOR.JK": "Mayora Indah Tbk.",
    "GGRM.JK": "Gudang Garam Tbk.",
    "HMSP.JK": "H.M. Sampoerna Tbk.",
    "EXCL.JK": "XL Axiata Tbk.",
    "ISAT.JK": "Indosat Ooredoo Hutchison Tbk.",
    "TOWR.JK": "Sarana Menara Nusantara Tbk.",
    "TBIG.JK": "Tower Bersama Infrastructure Tbk.",
    "MEDC.JK": "Medco Energi Internasional Tbk.",
    "AKRA.JK": "AKR Corporindo Tbk.",
    "JSMR.JK": "Jasa Marga (Persero) Tbk.",
    "SMGR.JK": "Semen Indonesia (Persero) Tbk.",
    "INTP.JK": "Indocement Tunggal Prakarsa Tbk.",
    "ADMR.JK": "Adaro Minerals Indonesia Tbk.",
    "ARTO.JK": "Bank Jago Tbk.",
    "BUMI.JK": "Bumi Resources Tbk.",
    "BBTN.JK": "Bank Tabungan Negara (Persero) Tbk.",
    "PNLF.JK": "Panin Financial Tbk.",
    "BSDE.JK": "Bumi Serpong Damai Tbk.",
    "PWON.JK": "Pakuwon Jati Tbk.",
    "CTRA.JK": "Ciputra Development Tbk.",
    "SMRA.JK": "Summarecon Agung Tbk.",
    "WIKA.JK": "Wijaya Karya (Persero) Tbk.",
    "PTPP.JK": "PP (Persero) Tbk.",
    "ADHI.JK": "Adhi Karya (Persero) Tbk.",
    "SSMS.JK": "Sawit Sumbermas Sarana Tbk.",
    "LSIP.JK": "London Sumatra Indonesia Tbk.",
    "AALI.JK": "Astra Agro Lestari Tbk.",
    "DSNG.JK": "Dharma Satya Nusantara Tbk.",
    "SIDO.JK": "Industri Jamu dan Farmasi Sido Muncul Tbk.",
    "ACES.JK": "Aspirasi Hidup Indonesia Tbk. (Ace Hardware)",
    "MAPI.JK": "Mitra Adiperkasa Tbk.",
    "ERAA.JK": "Erajaya Swasembada Tbk.",
    "BIRD.JK": "Blue Bird Tbk.",
    "MBMA.JK": "Merdeka Battery Materials Tbk.",
    "NCKL.JK": "Trimegah Bangun Persada Tbk. (Harita Nickel)",
    "HEAL.JK": "Medikaloka Hermina Tbk. (RS Hermina)",
    "MIKA.JK": "Mitra Keluarga Karyasehat Tbk.",
    "SILO.JK": "Siloam International Hospitals Tbk.",
    "BUKA.JK": "Bukalapak.com Tbk.",
    "SCMA.JK": "Surya Citra Media Tbk.",
    "MNCN.JK": "Media Nusantara Citra Tbk.",
    "AUTO.JK": "Astra Otoparts Tbk.",
    "IMAS.JK": "Indomobil Sukses Internasional Tbk."
}
